### ISSUE TITLE
Clarification for "careful: if the ray or min_t lands inside the box this could still hit something stored inside the box, so this counts as a hit "

### ISSUE THREAD

**Issue by velociraptor111** [alecjacobson/computer-graphics-bounding-volume-hierarchy#5]
What does this warning mean ? " careful: if the ray or min_t lands inside the box this could still hit something stored inside the box, so this counts as a hit ". 

Also, from my understanding of the variable **t**, it should hold the parametric distance of the ray to the _first_ hit of the box on the edges.  So what does the sentence "min_t lands inside the box" really mean?

**Comment by alecjacobson** [comment]
Could you give this issue (and all future issues) a better title?

**Comment by alecjacobson** [comment]
Consider the case where the ray originates from inside the box and the box contains a triangle that the ray hits.

**Comment by zhtdavis** [comment]
I think for ray_intersect_box you only need to check whether the ray hits the box or not, you don't to find the exact t value. You need to find the exact t value when you are doing intersection test for an actual object(not box). Only actual object will be the leaf for the tree. Since we are doing a post order traversal on the tree, the resulting t value will populate upward. 

That's my current understanding on the material before the class. Correct me if I'm wrong.
